### ISSUE TITLE
Experiments: remove non-numerical values from 510__0

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#192]
Just two records in Experiments have a non-numerical value in `510__0`: https://inspirehep.net/search?ln=en&cc=Experiments&p=510__0%3A%2F%5B%5E0-9%5D%2F&action_search=Search&sf=experimentname&so=a

Since they are just two I believe this is better handled by manual curation (@annetteholtkamp).

**Comment by annetteholtkamp** [comment]
fixed - Annette


On 18 Jul 2016, at 21:34, Jacopo Notarstefano <notifications@github.com<mailto:notifications@github.com>> wrote:


Just two records in Experiments have a non-numerical value in 510__0: https://inspirehep.net/search?ln=en&cc=Experiments&p=510__0%3A%2F%5B%5E0-9%5D%2F&action_search=Search&sf=experimentname&so=a

Since they are just two I believe this is better handled by manual curation (@annetteholtkamp<https://github.com/annetteholtkamp>).

**Comment by jacquerie** [comment]
Thanks!
