### ISSUE TITLE
HEPNames: which ID schemes we want to preserve?

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire#211]
Here is the current status of `035__9` in HEPNames:
```
   1 A.H.Sanjari.1
   1 BAi
   1 BIA
   1 L.Santoni.1
   1 ORCKD
   1 R.Mohayaee.1
   1 ResearchID
   1 SPIRES
   1 Scopus
   1 TWITTER
   1 WikiPedia
   2 ORCI
   2 RESEARCHERID
   3 ORICD
   4 ResearcherID
   4 SCOPUS
   5 ORCiD
  24 VIAF
  65 GoogleScholar
 139
 215 JACOW
 223 Wikipedia
 275 ARXIV
 779 DESY
 903 SLAC
1677 KAKEN
1915 arXiv
8991 CERN
8998 ORCID
53694 INSPIRE
58685 BAI
```

After correcting the obvious mistakes we get the following ID schemes:
```
    1 SPIRES
    1 TWITTER
    5 SCOPUS
    7 RESEARCHERID
   24 VIAF
   65 GOOGLESCHOLAR
  215 JACOW
  224 WIKIPEDIA
  779 DESY
  903 SLAC
 1677 KAKEN
 2190 ARXIV
 8991 CERN
 9009 ORCID
53694 INSPIRE
58687 BAI
```

Which ones do we want to preserve? Could you help me add their expected format to the [schema](https://github.com/inspirehep/inspire-next/blob/25296a555b052951455acee34b09cdecfa63702f/inspirehep/modules/records/jsonschemas/records/elements/id.json)? I'm currently missing SLAC, GOOGLESCHOLAR, VIAF, RESEARCHERID, SCOPUS, TWITTER, SPIRES of the above list.

**Comment by kaplun** [comment]
@inspirehep/inspire-content

**Comment by kaplun** [comment]
@jacquerie, TWITTER and GOOGLESCHOLAR represent regular Twitter and Scholar IDs. For Twitter this is an arbitrary string, for Scholar it's an arbitrary horrible string decided by Scholar itself.

* VIAF it's: https://viaf.org/ and the ID is a long integer
* RESEARCHERID: is http://www.researcherid.com/, I.e. Thomson Reuters pre-ORCID initiative . The regexp could be `[A-z]{1}-\d{4}-\d{4}`(see http://community.thomsonreuters.com/t5/ResearcherID-General/ResearchID-Identifier-Format/td-p/57000)
* SCOPUS: is https://www.scopus.com/, i.e. Elsevier pre-ORCID initiative. The ID is a long int
* SPIRES: should have been INSPIRE ;-)

**Comment by kaplun** [comment]
P.s. for Twitter I am surprised it's only one. @inspirehep/inspire-content  ?
For SLAC I don't know but I assume it's an integer and has the same potential of the CERN CCIDs (i.e. allowing to match internal directories with INSPIRE).

**Comment by kaplun** [comment]
To make the story short: we want to preserve all of these IDs. Because they all contribute to either disambiguation or to follow on the profile of a person into external services.

**Comment by jacquerie** [comment]
> P.s. for Twitter I am surprised it's only one.

This is because this information is usually stored in `8564_`: https://inspirehep.net/search?ln=en&cc=HepNames&ln=en&cc=HepNames&p=8564_y%3A%27twitter%27&of=text&ot=8564_

So that record is the outlier, and it should be harmonized with the others.

**Comment by kaplun** [comment]
Mmh I am not sure. This is similar to the discussion of the other day, re: URL Vs. IDs. A twitter account is a valuable identifier. I think we could migrate URLs to twitter to become real identifiers. Maybe this has not been done in the past because we don't display twitter accounts at the moment.

CC @inspirehep/inspire-content

**Comment by annetteholtkamp** [comment]
I think the twitter id’s have never been moved to 035. What else do we have that should be treated as an ID? linkedin? wikipedia? ResearcherID?
They should also be explicitly listed in the user addition/update form.

- Annette


On 24 Aug 2016, at 22:45, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


Mmh I am not sure. This is similar to the discussion of the other day, re: URL Vs. IDs. A twitter account is a valuable identifier. I think we could migrate URLs to twitter to become real identifiers. Maybe this has not been done in the past because we don't display twitter accounts at the moment.

CC @inspirehep/inspire-content<https://github.com/orgs/inspirehep/teams/inspire-content>
