### ISSUE TITLE
Collaboration display in HEP

### ISSUE THREAD

**Issue by tsgit** [inspirehep/inspire#251]
https://rt.inspirehep.net/Ticket/Display.html?id=626193

In case the previous comment was not clear:

Collaboration is stripped from the content of 710__g and added as default by the display formats.
But Group, Consortium, ... stay in the metadata.
I vaguely remember that somewhere sometime there were exceptions that 'Collaboration' is not added to such fields on display. But my memory might be wrong.

Fact is that
http://inspirehep.net/search?ln=en&amp;p=710__g%3A%2FGroup%24%2F&amp;of=hb&amp;action_search=Search
looks stupid.

In this particular case there is an additional problem since "Heavy Flavor Averaging Group (HFAG)" doesn't end in group.
Here we can decide whether we want to change the code or the metadata.
But I can't ask that guy whether he is OK if I rename it to
"Heavy Flavor Averaging Group" if that doesn't work either.
And if someone is touching the code we might take care of 'group' in the middle of the string too.

------------------------------------------------------------------------------------
well it's not so simple. the code

https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_authors.py#L291-L295

assumes e.g.

 ['Atlas', 'CMS'] => Atlas and CMS Collaborations

 ['Atlas', 'Heavy Group', 'Foo Team', 'CMS'] => Atlas and Heavy Group and Foo Team and CMS Collaborations

if I skip "collaboration(s)" at the end when there is a Group or Team or somesuch it looks odd

if I add Collaboration to each term not containing Group, Team, etc. then it becomes lengthy

Atlas Collaboration and Heavy Group and Foo Team and CMS Collaboration

and then some extra logic could be applied to different order

Atlas and CMS Collaborations and Heavy Group and Foo Team

in addition to "Collaboration", "Consortium", "Group", "Working Group", "Team", "Task Force"  I see things in 710__g like

"Le Groupeur Lineaire de SPIRAL"
"Groupe De L'Aimant De La Division Du Synchrotron À Protons"
"Crew of the Intensity Upgrade Study"
"Indian Association for the Cultivation of Science"
"Sanford Laboratory at Homestake"
"Center for Theoretical Astrophysics, Los Alamos National Lab"
"The Abdus Salam International Centre for Theoretical Physics"

**Comment by tsgit** [comment]
https://github.com/inspirehep/inspire/pull/253

**Comment by ksachs** [comment]
That's why I wanted an additional field for the display string. For indexing we need ALTAS and CMS separately, for display there are too many special cases to do it properly fully automatic.

I guess a simplified rule that doesn't add Collaboration(s) if there are only ["Consortium", "Group", "Working Group", "Team", "Task Force"] would already improve the situation. For mixed stuff it always looks ugly. Up to you how much time you want to waste on this on legacy. 

And you found some 'non collaborations' that ended up in 710__g because 'for theory' triggers the 'for the' condition. I'll take care of those (again).
