### ISSUE TITLE
Google Scholar indexing issues

### ISSUE THREAD

**Issue by lnielsen** [inspirehep/inspire#315]
Following two issues have been reported for other Invenio 1.x installations:

1. Authors/supervisors/... are mixed in ``citation_authors`` (inveniosoftware/invenio#3825)
2. Subtitles are included in ``citation_title`` (inveniosoftware/invenio#3826)

This affects Google Scholar indexing negatively. It seems like INSPIRE is affected by (2) see e.g. http://inspirehep.net/record/1605974 but not (1) see e.g. http://inspirehep.net/record/1426906

Note that the corresponding record on CDS for (2) does not have the issue (https://cds.cern.ch/record/2275142?ln=en)

**Comment by annetteholtkamp** [comment]
Should we envisage to break titles after the first instance of  “: “?

- Annette

On 16 Aug 2017, at 16:38, Lars Holm Nielsen <notifications@github.com<mailto:notifications@github.com>> wrote:


Following two issues have been reported for other Invenio 1.x installations:

  1.  Authors/supervisors/... are mixed in citation_authors (inveniosoftware/invenio#3825<https://github.com/inveniosoftware/invenio/issues/3825>)
  2.  Subtitles are included in citation_title (inveniosoftware/invenio#3826<https://github.com/inveniosoftware/invenio/issues/3826>)

This affects Google Scholar indexing negatively. It seems like INSPIRE is affected by (2) see e.g. http://inspirehep.net/record/1605974 but not (1) see e.g. http://inspirehep.net/record/1426906

Note that the corresponding record on CDS for (2) does not have the issue (https://cds.cern.ch/record/2275142?ln=en)

**Comment by lnielsen** [comment]
I think the problem in http://inspirehep.net/record/1605974 is that the title and subtitle is not concatenated with ``:``. E.g. the MARC is:

```
245__ $$aThe CAST Experiment$$bStatus and Perspectives
```

which results in the following HTML meta-tag:

```html
<meta content="The CAST Experiment" name="citation_title" />
```

but the tag should be:

```html
<meta content="The CAST Experiment: Status and Perspectives" name="citation_title" />
```

(to allow scholar to do better citation analysis).

I don't think it's a big issue, given that only around 5k records have ``245__b``.

**Comment by annetteholtkamp** [comment]
Sorry, I misunderstood. So it’s just the other way around.

Actually, this issue is growing in importance in Inspire since we didn’t have subtitles on Spires. And it seems to be an even bigger problem for CDS where there are 34,000 articles and preprints with 245__b.

I’m surprised that this is an issue since 245__b is a perfectly legal marc21 tag. Isn’t this then a problem for many services?

- Annette

On 16 Aug 2017, at 20:38, Lars Holm Nielsen <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the problem in http://inspirehep.net/record/1605974 is that the title and subtitle is not concatenated with :. E.g. the MARC is:

245__ $$aThe CAST Experiment$$bStatus and Perspectives


which results in the following HTML meta-tag:

<meta content="The CAST Experiment" name="citation_title" />

but the tag should be:

<meta content="The CAST Experiment: Status and Perspectives" name="citation_title" />

(to allow scholar to do better citation analysis).

I don't think it's a big issue, given that only around 5k records have 245__b.

**Comment by lnielsen** [comment]
I've found that CDS seems to have made a [custom fix](https://github.com/CERNDocumentServer/invenio/commit/d1790c9cc47e52779bce6bea1d7d1512a59a596a) which can probably just be used as a quick fix on Inspire. 

And yes, this is an issue for many other installations such as e.g. ddd.uab.cat and doc.rero.ch

**Comment by michamos** [comment]
@tsgit can you take care of it?

**Comment by tsgit** [comment]
the [custom fix](https://github.com/CERNDocumentServer/invenio/commit/d1790c9cc47e52779bce6bea1d7d1512a59a596a)
assumes implicit ordering in `bfo.fields` and preservation of that order in the `dict`. I prefer to make that explicit
`out.append(' : '.join([val[k] for k in sorted(val.keys())]))`
